version: '3'
services:
  nextjs-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nodejs-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"