version: '3'

services:
  nodejs-app:
    build: ./server
    ports:
      - "5000:5000"

  nextjs-app:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://nodejs-app:5000
