# docker-compose.yml

version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:5000/data
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
