---
name: Deploy Next.js and Node.js applications to EC2

on:
  push:
    branches:
      - main

# on:
#   workflow_run:
#     workflows: ["Deploy Infrastructure"]
#     types:
#       - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy app directory to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r app ubuntu@13.250.50.133:~/app