---
name: Deploy Next.js and Node.js applications to EC2

on:
  push:
    branches:
      - main

# on:
#   workflow_run:
#     workflows: ["Deploy Infrastructure"]
#     types:
#       - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy app directory to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r app ubuntu@13.250.50.133:~/app
      
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.250.50.133 << 'EOF'
          # Update and install dependencies
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y nodejs npm

          # Install PM2 for process management
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          echo "NEXT_PUBLIC_API_URL=http://13.250.50.133:5000" > ~/app/client/.env.local

          # Start Node.js backend
          cd ~/app/server
          npm install
          pm2 start index.js --name "nodejs-server"


          # Start Next.js app
          cd ~/app/client
          npm install
          npm run build
          pm2 start npm --name "nextjs-app" -- start
          EOF