name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Pulumi CLI
        run: npm install -g pulumi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # - name: Set public key as github env
      #   run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Install project dependencies
        run: npm install
        working-directory: Infra

      - name: Select Pulumi stack
        run: pulumi stack select Konami33/Nextjs-Nodejs-Infra/dev --cwd Infra

      - name: Refresh Pulumi stack
        run: pulumi refresh --yes --cwd Infra

      - name: Deploy infrastructure with Pulumi
        run: pulumi up --yes --cwd Infra
